<?php

$cminds_plugin_config = array(
    'plugin-is-pro' => TRUE,
    'plugin-has-addons' => FALSE,
    'plugin-version' => com\cminds\rssaggregator\App::VERSION,
    'plugin-abbrev' => com\cminds\rssaggregator\App::SLUG,
    'plugin-short-slug' => com\cminds\rssaggregator\App::SLUG,
    'plugin-parent-short-slug' => '',
    'plugin-affiliate' => '',
    'plugin-show-guide' => FALSE,
    'plugin-guide-text' => '<p>Using the CM Curated RSS Aggregator you can create unlimited amount of curated lists of links grouped by categories and tags.</p><p>Each link has its own description and favicon. Lists have easy search and filtering utilities.</p>',
    'plugin-guide-video-height' => 180,
    'plugin-guide-videos' => array(
//        array('title' => 'Video #1 title', 'video_id' => '134490629'),
//        array('title' => 'Video #2 title', 'video_id' => '134490629'),
//        array('title' => 'Video #3 title', 'video_id' => '134490629'),
    ),
    'plugin-redirect-after-install' => admin_url('admin.php?page=cmra-options'),
    'plugin-file' => com\cminds\rssaggregator\App::PLUGIN_FILE,
    'plugin-dir-path' => plugin_dir_path(com\cminds\rssaggregator\App::PLUGIN_FILE),
    'plugin-dir-url' => plugin_dir_url(com\cminds\rssaggregator\App::PLUGIN_FILE),
    'plugin-basename' => plugin_basename(com\cminds\rssaggregator\App::PLUGIN_FILE),
    'plugin-icon' => '',
    'plugin-name' => com\cminds\rssaggregator\App::PLUGIN_NAME_EXTENDED,
    'plugin-license-name' => com\cminds\rssaggregator\App::PLUGIN_NAME_EXTENDED,
    'plugin-slug' => '',
    'plugin-menu-item' => com\cminds\rssaggregator\App::SLUG,
    'plugin-textdomain' => com\cminds\rssaggregator\App::SLUG,
    'plugin-userguide-key' => '882-curated-rss-aggregator-cmcra',
    'plugin-store-url' => 'https://www.cminds.com/wordpress-plugins-library/curated-wordpress-rss-aggregator-plugin-by-creativeminds/',
    'plugin-support-url' => '',
    'plugin-review-url' => '',
    'plugin-changelog-url' => 'https://www.cminds.com/wordpress-plugins-library/curated-wordpress-rss-aggregator-plugin-by-creativeminds/#changelog',
    'plugin-licensing-aliases' => array(com\cminds\rssaggregator\App::PLUGIN_NAME_EXTENDED),
);
