<?php

use com\cminds\rssaggregator\plugin\options\Options;
use com\cminds\rssaggregator\plugin\helpers\HTMLHelper;
use com\cminds\rssaggregator\plugin\taxonomies\TagTaxonomy;
use com\cminds\rssaggregator\plugin\shortcodes\Shortcode;
?>
<div class="clear"></div>
<hr />

<?php
//echo do_shortcode('[cminds_free_ads]');
?>

<div class="cmra">
    <div class="card">
        <h2>Shortcodes</h2>
        <ol>
            <li>
                to display list use
                <code>[<?php echo Shortcode::SHORTCODE; ?>]</code> with <code>list</code>, <code>category</code> and <code>tag</code> attributes (you can use then at the same time to customize your list &mdash; they works like filters) where:
                <ul>
                    <li>
                        <code>list</code> is slug or list of slugs of <a href="edit-tags.php?taxonomy=cmra_list">lists</a>, e.g.: <code>[<?php echo Shortcode::SHORTCODE; ?> list=list1,list2,...]</code>,
                    </li>
                    <li>
                        <code>category</code> is slug or list of slugs of <a href="edit-tags.php?taxonomy=cmra_category">categories</a>, e.g.: <code>[<?php echo Shortcode::SHORTCODE; ?> category=category1,category2,...]</code>,
                    </li>
                    <li>
                        <code>tag</code> is slug or list of slugs of <a href="edit-tags.php?taxonomy=cmra_tag">tags</a>, e.g.: <code>[<?php echo Shortcode::SHORTCODE; ?> tag=tag1,tag2,...]</code>,
                    </li>
                </ul>
            </li>
            <li>
                to display single category (without search and filter on the top of the list) use
                <code>[<?php echo Shortcode::SHORTCODE; ?> category=category1]</code> where <code>category</code> attribute is slug of the <a href="edit-tags.php?taxonomy=cmra_category">category</a>.
            </li>
        </ol>
        <p>
            To overwrite global setting of max number of links use <code>max_links</code> attribute (set 0 to remove limit) e.g.: <code>[<?php echo Shortcode::SHORTCODE; ?> category=category1 max_links=10]</code>.
        </p>
    </div>
    <h2 class="nav-tab-wrapper">
        <a href="#cmra-tab-plugin-options" data-for="general-options" class="nav-tab">Plugin Options</a>
        <a href="#cmra-tab-plugin-appearance" data-for="plugin-appearance" class="nav-tab">Plugin Appearance</a>
        <a href="#cmra-tab-plugin-diagnostics" data-for="plugin-diagnostics" class="nav-tab" style="float: right;"><small>Plugin Diagnostics</small></a>
    </h2>
    <form method="post">
        <div data-role="tab" data-tab="general-options" style="display: none;">
            <h3>General</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="columns_count">Number of columns *</label></th>
                    <td>
                        <input name="columns_count" type="number" min="1" max="10" id="columns_count" value="<?php echo intval(Options::getOption('columns_count')); ?>" class="regular-text" required="required">
                        <p class="description">Number of columns generated by plugin.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="max_number_of_links">Max number of links</label></th>
                    <td>
                        <input name="max_number_of_links" type="number" min="0" id="max_number_of_links" value="<?php echo intval(Options::getOption('max_number_of_links')) ?: ''; ?>" class="regular-text">
                        <p class="description">Max number of links displayed in categories.<br />Leave empty to remove limit.</p>
                    </td>
                </tr>
                <!--
                <tr>
                    <th scope="row"><label for="favicons_local_cache">Favicons local cache</label></th>
                    <td>
                        <input type="checkbox" id="favicons_local_cache" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('favicons_local_cache')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="favicons_local_cache" value="<?php echo intval(Options::getOption('favicons_local_cache')); ?>" />
                        <p class="description">
                            Images with favicons will be locally saved as attached - this options <strong>is not</strong> recommend if you curate large lists (may cause performance issues).
                            <br />
                            Favicon for link is cached during adding or updating link entry.
                        </p>
                    </td>
                </tr>
                -->
                <tr>
                    <th scope="row"><label for="links_rel_nofollow">No follow</label></th>
                    <td>
                        <input type="checkbox" id="links_rel_nofollow" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('links_rel_nofollow')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="links_rel_nofollow" value="<?php echo intval(Options::getOption('links_rel_nofollow')); ?>" />
                        <p class="description">
                            <code>rel="nofollow"</code> will be added to links.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="links_target_blank">Open in a new window or tab</label></th>
                    <td>
                        <input type="checkbox" id="links_target_blank" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('links_target_blank')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="links_target_blank" value="<?php echo intval(Options::getOption('links_target_blank')); ?>" />
                        <p class="description">
                            Linked documents will be opened in a new window or tab.
                        </p>
                    </td>
                </tr>
                <?php /*
                  <tr>
                  <th scope="row"><label for="show_checkboxes">Show checkboxes</label></th>
                  <td>
                  <input type="checkbox" id="show_checkboxes" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_checkboxes')) ? 'checked="checked"' : ''; ?> />
                  <input type="hidden" name="show_checkboxes" value="<?php echo intval(Options::getOption('show_checkboxes')); ?>" />
                  <p class="description">
                  Show checkboxes before links which allow users mark visited addresses.
                  </p>
                  </td>
                  </tr>
                 */ ?>
                <tr>
                    <th scope="row"><label for="show_favicons">Show favicons</label></th>
                    <td>
                        <input type="checkbox" id="show_favicons" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_favicons')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_favicons" value="<?php echo intval(Options::getOption('show_favicons')); ?>" />
                        <p class="description">
                            Show favicons before links.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_subtitles">Show subtitles</label></th>
                    <td>
                        <input type="checkbox" id="show_subtitles" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_subtitles')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_subtitles" value="<?php echo intval(Options::getOption('show_subtitles')); ?>" />
                        <p class="description">
                            Show subtitles with description under links.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_tooltips">Show tooltips</label></th>
                    <td>
                        <input type="checkbox" id="show_tooltips" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_tooltips')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_tooltips" value="<?php echo intval(Options::getOption('show_tooltips')); ?>" />
                        <p class="description">
                            Show tooltips with description on links hover.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_images">Show thumbnails</label></th>
                    <td>
                        <input type="checkbox" id="show_images" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_images')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_images" value="<?php echo intval(Options::getOption('show_images')); ?>" />
                        <p class="description">
                            Show thumbnails from feeds in links.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_big_images">Show big images</label></th>
                    <td>
                        <input type="checkbox" id="show_big_images" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_big_images')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_big_images" value="<?php echo intval(Options::getOption('show_big_images')); ?>" />
                        <p class="description">
                            Show big images below links.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_sources">Show sources</label></th>
                    <td>
                        <input type="checkbox" id="show_sources" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_sources')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_sources" value="<?php echo intval(Options::getOption('show_sources')); ?>" />
                        <p class="description">
                            Show RSS feeds name under links.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_dates">Show dates</label></th>
                    <td>
                        <input type="checkbox" id="show_dates" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_dates')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_dates" value="<?php echo intval(Options::getOption('show_dates')); ?>" />
                        <p class="description">
                            Show dates under links.
                        </p>
                    </td>
                </tr>
            </table>
            <h3>Search and filter</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="show_search_and_filter">Show search and filter</label></th>
                    <td>
                        <input type="checkbox" id="show_search_and_filter" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_search_and_filter')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_search_and_filter" value="<?php echo intval(Options::getOption('show_search_and_filter')); ?>" />
                        <p class="description">
                            Show upper search field and categories filter.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_bonus_info">Show additional information</label></th>
                    <td>
                        <input type="checkbox" id="show_bonus_info" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_bonus_info')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_bonus_info" value="<?php echo intval(Options::getOption('show_bonus_info')); ?>" />
                        <p class="description">
                            Show additional information below search field.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="bonus_info_format">Additional information format</label></th>
                    <td>
                        <input name="bonus_info_format" type="text" id="bonus_info_format" value="<?php echo esc_attr(Options::getOption('bonus_info_format')); ?>" class="large-text">
                        <p class="description">Additional information displayed below search filed.<br /> Use <code>{last-update-date}</code> placeholder to display list last update date and <code>{links-count}</code> to display number of links.<br />You can use HTML entities (for example <code>&lt;br /&gt;</code> or <code>&lt;code&gt;</code>) to customize information format.</p>
                    </td>
                </tr>
            </table>
            <h3>Links order</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="link_order_by">Order by</label></th>
                    <td>
                        <select name="link_order_by">
                            <?php
                            foreach (array(
                        'name_asc' => 'By name ascending',
                        'name_desc' => 'By name descending',
                        'edit_time_asc' => 'By date ascending',
                        'edit_time_desc' => 'By date descending'
                            ) as $key => $value) {
                                echo sprintf('<option value="%s" %s> %s</option>', $key, $key == Options::getOption('link_order_by') ? 'selected="selected"' : '', $value);
                            }
                            ?>
                        </select>
                        <p class="description">Determine how RSS links will be sorted.</p>
                    </td>
                </tr>
            </table>
            <h3>"NEW" tag</h3>
            <p>
                This feature allows you to automatically add tag to new or just edited links for specified time.
            </p>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="new_tag_id">Tag</label></th>
                    <td>
                        <?php
                        wp_dropdown_categories(array(
                            'show_option_none' => '&nbsp;',
                            'hide_empty' => FALSE,
                            'selected' => Options::getOption('new_tag_id'),
                            'name' => 'new_tag_id',
                            'id' => 'new_tag_id',
                            'taxonomy' => TagTaxonomy::TAXONOMY,
                        ));
                        ?>
                        <p class="description">
                            "NEW" tag - added to new or updated links entries (leave empty to disable "NEW" tag feature).
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="new_tag_duration">Duration</label></th>
                    <td>
                        <select name="new_tag_duration" id="new_tag_duration">
                            <?php
                            foreach (array(
                        '1 day' => 86400,
                        '2 days' => 172800,
                        '3 days' => 259200,
                        '5 days' => 432000,
                        '1 week' => 604800,
                        '2 weeks' => 1209600,
                        '1 month' => 2419200,
                        '3 months' => 7257600
                            ) as $k => $v) {
                                echo sprintf('<option value="%s" %s>%s</option>', $v, Options::getOption('new_tag_duration') == $v ? 'selected="selected"' : '', $k);
                            }
                            ?>
                        </select>
                        <p class="description">
                            How long "NEW" tag will be added.
                            <br />
                            Remember, if "NEW" tag is assigned directly to link, this option will not affect displaying it.
                        </p>
                    </td>
                </tr>
            </table>
        </div>
        <div data-role="tab" data-tab="plugin-appearance" style="display: none;">
            <h3>Categories</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="category_font_size">Font size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('category_font_size', Options::getOption('category_font_size'), array('class' => 'regular-text', 'id' => 'category_font_size')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="category_background_color">Background color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('category_background_color', Options::getOption('category_background_color'), array('class' => 'regular-text', 'id' => 'tooltip_bg_color')); ?>
                        <p class="description">Category title background color (clear to use default).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="category_text_color">Text color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('category_text_color', Options::getOption('category_text_color'), array('class' => 'regular-text', 'id' => 'category_text_color')); ?>
                        <p class="description">Category title text color (clear to use default).</p>
                    </td>
                </tr>
            </table>
            <h3>RSS Links</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="link_max_words_count">Title max words count</label></th>
                    <td>
                        <input name="link_max_words_count" type="number" min="1" id="link_max_words_count" value="<?php echo esc_attr(Options::getOption('link_max_words_count')); ?>" class="regular-text">
                        <p class="description">Titles text will be trim if longer.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_subtitle_max_words_count">Description max words count</label></th>
                    <td>
                        <input name="link_subtitle_max_words_count" type="number" min="1" id="link_subtitle_max_words_count" value="<?php echo esc_attr(Options::getOption('link_subtitle_max_words_count')); ?>" class="regular-text">
                        <p class="description">RSS links descriptions text will be trim if longer.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_font_size">Title font size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('link_font_size', Options::getOption('link_font_size'), array('class' => 'regular-text', 'id' => 'link_font_size')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_subtitle_font_size">Description font size</label></th>
                    <td>
                        <?php echo HTMLHelper::inputFontSize('link_subtitle_font_size', Options::getOption('link_subtitle_font_size'), array('class' => 'regular-text', 'id' => 'link_subtitle_font_size')); ?>
                        <p class="description">Leave empty to use default.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="show_link_subtitle_indent">Indent description</label></th>
                    <td>
                        <input type="checkbox" id="show_link_subtitle_indent" onchange="jQuery(this).next().val(this.checked ? 1 : 0)" <?php echo intval(Options::getOption('show_link_subtitle_indent')) ? 'checked="checked"' : ''; ?> />
                        <input type="hidden" name="show_link_subtitle_indent" value="<?php echo intval(Options::getOption('show_link_subtitle_indent')); ?>" />
                        <p class="description">
                            Descriptions text will be indent.
                        </p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_hover_color">Hover background color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('link_hover_color', Options::getOption('link_hover_color'), array('class' => 'regular-text', 'id' => 'link_hover_color')); ?>
                        <p class="description">Links hover background color (clear to use default).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_image_height">Image height</label></th>
                    <td>
                        <input name="link_image_height" type="text" id="link_image_height" value="<?php echo esc_attr(Options::getOption('link_image_height')); ?>" class="regular-text" placeholder="e.g. 30px">
                        <p class="description">Height of images in links. Leave empty for auto size.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_image_width">Image width</label></th>
                    <td>
                        <input name="link_image_width" type="text" id="link_image_width" value="<?php echo esc_attr(Options::getOption('link_image_width')); ?>" class="regular-text" placeholder="e.g. 30px">
                        <p class="description">Width of images in links. Leave empty for auto size.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="link_date_format">Date format</label></th>
                    <td>
                        <input name="link_date_format" type="text" id="link_date_format" value="<?php echo esc_attr(Options::getOption('link_date_format')); ?>" class="regular-text" placeholder="e.g. Y-m-d H:i:s">
                        <p class="description">Date format compatible with PHP date function.<br />See <a href="https://secure.php.net/manual/en/function.date.php" target="_blank">https://secure.php.net/manual/en/function.date.php</a> for more informations.</p>
                    </td>
                </tr>
            </table>
            <h3>Tooltips</h3>
            <table class="form-table">
                <tr>
                    <th scope="row"><label for="tooltip_max_words_count">Max words count</label></th>
                    <td>
                        <input name="tooltip_max_words_count" type="number" min="1" id="tooltip_max_words_count" value="<?php echo esc_attr(Options::getOption('tooltip_max_words_count')); ?>" class="regular-text">
                        <p class="description">Tooltips text will be trim if longer.</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="tooltip_background_color">Background color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('tooltip_background_color', Options::getOption('tooltip_background_color'), array('class' => 'regular-text', 'id' => 'tooltip_bg_color')); ?>
                        <p class="description">Tooltips background color (clear to use default).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="tooltip_border_color">Border color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('tooltip_border_color', Options::getOption('tooltip_border_color'), array('class' => 'regular-text', 'id' => 'tooltip_bg_color')); ?>
                        <p class="description">Tooltips border color (clear to use default).</p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><label for="tooltip_text_color">Text color</label></th>
                    <td>
                        <?php echo HTMLHelper::inputColor('tooltip_text_color', Options::getOption('tooltip_text_color'), array('class' => 'regular-text', 'id' => 'tooltip_bg_color')); ?>
                        <p class="description">Tooltips text color (clear to use default).</p>
                    </td>
                </tr>
            </table>
        </div>
        <div id="cmra-form-submit" style="display: none;">
            <input type="hidden" name="cmra_action_update" value="1" />
            <input type="hidden" name="nonce" value="<?php echo wp_create_nonce('cmra_action_update'); ?>" />
            <?php submit_button(); ?>
            <small>* - required fields</small>
        </div>
    </form>
    <div data-role="tab" data-tab="plugin-diagnostics" style="display: none;">
        <?php do_action('cmra_options_diagnostic_tab'); ?>
    </div>
</div>

<style type="text/css">
    .cmra h2.nav-tab-wrapper{
        margin-top: 20px;
    }
    .cmra .nav-tab{
        box-shadow: none;
    }
    .cmra .card{
        max-width: none;
    }
</style>
<script type="text/javascript">
    (function ($) {
        "use strict";
        $('.cmra .nav-tab').on('click', function () {
            $('.cmra .nav-tab').removeClass('nav-tab-active');
            $(this).addClass('nav-tab-active');
            $('.cmra *[data-role="tab"]').hide();
            $('.cmra *[data-role="tab"][data-tab="' + $(this).data('for') + '"]').show();
            if ($(this).data('for') == 'plugin-diagnostics') {
                $('#cmra-form-submit').hide();
            } else {
                $('#cmra-form-submit').show();
            }
        });
        if ($('.cmra a[href="' + window.location.hash + '"]').click().length != 1) {
            $('.cmra a.nav-tab').first().click();
        }
        $('.cmra input[type="submit"]').on('click', function () {
            if ($('.cmra form').find(':invalid')) {
                var tab = $('.cmra form').find(':invalid').first().parents('*[data-role="tab"]').data('tab');
                $('.cmra').find('a[data-for="' + tab + '"]').click();
            }
        });
    })(jQuery);
</script>